guests = []
guests.append('Vova')
guests.append('Maksim')
guests.append('Masha')
print(guests)
print("Hello " + guests[0].title() + " go to eat!")
print("Hello " + guests[1].title() + " go to eat!")
print("Hello " + guests[2].title() + " go to eat!")
removed_guest = 'Masha'
guests.remove(removed_guest)
print(guests)
print(removed_guest)
guests.append('Natasha')
print("Hello " + guests[0].title() + " go to eat!")
print("Hello " + guests[1].title() + " go to eat!")
print("Hello " + guests[2].title() + " go to eat!")
print(len(guests))
guests.insert(0, 'Misha')
guests.insert(2, 'Tanya')
guests.insert(5, 'Sveta')
print(len(guests))
print("Hello " + guests[0].title() + " go to eat!")
print("Hello " + guests[1].title() + " go to eat!")
print("Hello " + guests[2].title() + " go to eat!")
print("Hello " + guests[3].title() + " go to eat!")
print("Hello " + guests[4].title() + " go to eat!")
print("Hello " + guests[5].title() + " go to eat!")
popped_guest = guests.pop()
print("i am sorry, but go home " + popped_guest)
popped_guest = guests.pop()
print("i am sorry, but go home " + popped_guest)
popped_guest = guests.pop()
print("i am sorry, but go home " + popped_guest)
popped_guest = guests.pop()
print("i am sorry, but go home " + popped_guest)
print(guests)
print("Go eat " + guests[0].title())
del guests[0]
print("Go eat " + guests[0].title())
del guests[0]

